@extends('layouts.app')

@section('content')
    <main class="app-page"><header class="page-header"><div><p class="eyebrow">Manajemen pengguna</p><h1>{{ $anggota->exists ? 'Edit Anggota' : 'Tambah Anggota' }}</h1><p class="muted">Siswa memakai NIS/NISN; guru dan karyawan memakai NIP.</p></div><a class="button button-secondary" href="{{ route('anggota.index') }}">Kembali</a></header>
        <section class="content-card form-card"><form method="POST" enctype="multipart/form-data" action="{{ $anggota->exists ? route('anggota.update', $anggota) : route('anggota.store') }}" class="form-stack">
            @csrf @if ($anggota->exists) @method('PUT') @endif
            <div class="form-grid"><div><label for="role">Peran</label><select id="role" name="role" required>@foreach (['Siswa', 'Guru', 'Karyawan'] as $nilaiRole)<option value="{{ $nilaiRole }}" @selected(old('role', $anggota->role ?: 'Siswa') === $nilaiRole)>{{ $nilaiRole }}</option>@endforeach</select>@error('role')<p class="field-error">{{ $message }}</p>@enderror</div><div><label for="status">Status anggota</label><select id="status" name="status" required>@foreach (['Aktif', 'Alumni', 'Nonaktif'] as $nilaiStatus)<option value="{{ $nilaiStatus }}" @selected(old('status', $anggota->status ?: 'Aktif') === $nilaiStatus)>{{ $nilaiStatus }}</option>@endforeach</select>@error('status')<p class="field-error">{{ $message }}</p>@enderror</div>
                <div><label for="nama">Nama lengkap</label><input id="nama" name="nama" value="{{ old('nama', $anggota->nama) }}" maxlength="150" required>@error('nama')<p class="field-error">{{ $message }}</p>@enderror</div><div><label for="email">Email <span class="optional">(opsional)</span></label><input id="email" name="email" type="email" value="{{ old('email', $anggota->email) }}" maxlength="150">@error('email')<p class="field-error">{{ $message }}</p>@enderror</div>
                <div><label for="nis_nisn">NIS / NISN</label><input id="nis_nisn" name="nis_nisn" value="{{ old('nis_nisn', $anggota->nis_nisn) }}" maxlength="30">@error('nis_nisn')<p class="field-error">{{ $message }}</p>@enderror</div><div><label for="nip">NIP</label><input id="nip" name="nip" value="{{ old('nip', $anggota->nip) }}" maxlength="30">@error('nip')<p class="field-error">{{ $message }}</p>@enderror</div>
                <div><label for="kelas">Kelas <span class="optional">(siswa)</span></label><input id="kelas" name="kelas" value="{{ old('kelas', $anggota->kelas) }}" maxlength="20">@error('kelas')<p class="field-error">{{ $message }}</p>@enderror</div><div><label for="jurusan">Jurusan <span class="optional">(siswa)</span></label><input id="jurusan" name="jurusan" value="{{ old('jurusan', $anggota->jurusan) }}" maxlength="100">@error('jurusan')<p class="field-error">{{ $message }}</p>@enderror</div>
                <div><label for="jabatan">Jabatan <span class="optional">(guru/karyawan)</span></label><input id="jabatan" name="jabatan" value="{{ old('jabatan', $anggota->jabatan) }}" maxlength="100">@error('jabatan')<p class="field-error">{{ $message }}</p>@enderror</div><div><label for="no_hp">Nomor HP <span class="optional">(opsional)</span></label><input id="no_hp" name="no_hp" value="{{ old('no_hp', $anggota->no_hp) }}" maxlength="20">@error('no_hp')<p class="field-error">{{ $message }}</p>@enderror</div>
                <div><label for="password">Password {{ $anggota->exists ? '(kosongkan bila tidak diubah)' : '' }}</label><input id="password" name="password" type="password" minlength="8" {{ $anggota->exists ? '' : 'required' }}>@error('password')<p class="field-error">{{ $message }}</p>@enderror</div><div><label for="password_confirmation">Konfirmasi password</label><input id="password_confirmation" name="password_confirmation" type="password" minlength="8"></div>
            </div>
            <div><label for="foto">Foto <span class="optional">(JPG, PNG, WEBP; maks. 2 MB)</span></label><input id="foto" name="foto" type="file" accept="image/jpeg,image/png,image/webp">@if ($anggota->foto)<p class="table-note">Foto saat ini: {{ basename($anggota->foto) }}</p>@endif @error('foto')<p class="field-error">{{ $message }}</p>@enderror</div>
            <button type="submit" class="button">{{ $anggota->exists ? 'Simpan perubahan' : 'Simpan anggota' }}</button>
        </form></section>
    </main>
@endsection
